"""
Hand-written descriptions merged into graph.json by extract_graph.py.

NODE_PURPOSE: one-line "what this file does", keyed by node id (project/path,
matching the ids extract_graph.py assigns). Transcribed from the inventory
reports in codebase_map/notes/ -- update here (not in graph.json directly)
when re-running the extractor, since graph.json is regenerated from scratch
each run.

TOOL_INFO: one-line "what this tool is / why a neuroimaging pipeline calls
it", keyed by the same tool names used in extract_graph.py's EXTERNAL_TOOLS.
"""

NODE_PURPOSE = {
    # --- KUL_NIS: master orchestrator + families ---
    "KUL_NIS/KUL_clinical_fmridti.sh": "Master clinical pipeline driver -- given -t 1..7 it scaffolds a study and runs BIDS conversion, fmriprep/dwiprep/freesurfer/fastsurfer, tumor segmentation, VBG, multiparc, FWT tractography, fMRI GLM, DSC perfusion, DTI-ALPS, and PACS/Karawun export end to end.",
    "KUL_NIS/KUL_dcm2bids.sh": "Converts a subject's raw DICOM to a BIDS dataset using dcm2niix + the Dcm2Bids Python package (current version).",
    "KUL_NIS/KUL_dcm2bids_new.sh": "Older DICOM->BIDS converter, despite the \"_new\" name -- still the one KUL_multisubjects_dcm2bids.sh actually calls (likely-unintentional drift).",
    "KUL_NIS/KUL_multisubjects_dcm2bids.sh": "Runs DICOM->BIDS conversion for every subject listed in a CSV, by calling KUL_dcm2bids_new.sh once per subject.",
    "KUL_NIS/KUL_dcm2bids.py": "Standalone DICOM-series-level NIfTI + tag extraction helper (orphan -- not wired into the automated pipeline).",
    "KUL_NIS/KUL_dwiprep.sh": "Core diffusion MRI preprocessing: denoise, degibbs, bias-correct, topup+eddy (dwifslpreproc), upsample, register to T1w, fit tensor/FOD models.",
    "KUL_NIS/KUL_dwiprep_anat.sh": "Registers preprocessed dMRI to the subject's T1w/FreeSurfer anatomy and builds anatomically-constrained tractography inputs (5ttgen).",
    "KUL_NIS/KUL_dwiprep_MNI.sh": "Warps dMRI-derived scalar maps (e.g. FA) into MNI standard space using fMRIPrep's own transform.",
    "KUL_NIS/KUL_dwiprep_fibertract.sh": "Named-project deterministic/probabilistic tractography script (early style, conceptually superseded by KUL_FWT).",
    "KUL_NIS/KUL_dwiprep_FT.sh": "Named-project (\"S61759\") fiber-tracking variant targeting specific major white-matter bundles.",
    "KUL_NIS/KUL_dwiprep_group_fba.sh": "Group-level fixel-based analysis: builds a population FOD template and normalises subjects onto it.",
    "KUL_NIS/KUL_dwiprep_group_fba_bkup.sh": "Backup/older copy of the group FBA script -- superseded, not the current path.",
    "KUL_NIS/KUL_fmriproc_conn.sh": "Runs a MELODIC-based automated fMRI analysis on fMRIPrep+AROMA output.",
    "KUL_NIS/KUL_fmriproc_nilearn_new.sh": "MATLAB-free first-level task-fMRI GLM using nilearn -- current engine.",
    "KUL_NIS/share/nilearn/KUL_fmriproc_nilearn_new.sh": "Stale, older duplicate of the top-level KUL_fmriproc_nilearn_new.sh -- missing later features, not the current path.",
    "KUL_NIS/KUL_fmriproc_spm_new.sh": "First-level task-fMRI GLM using MATLAB/SPM12.",
    "KUL_NIS/KUL_fmri_denoise.sh": "Post-fMRIPrep confound regression, bandpass filtering, and SUSAN smoothing of BOLD data.",
    "KUL_NIS/KUL_fmri_scrubbing.sh": "DVARS/framewise-displacement-based scrubbing (bad-volume removal) of resting-state fMRI.",
    "KUL_NIS/KUL_make_fMRI_labels.sh": "Interactive manual helper for hand-adding a single fMRI activation label into a Karawun export folder (not part of the automatic pipeline).",
    "KUL_NIS/KUL_run_rsfMRI_networks.sh": "Presurgical eloquent-cortex resting-state network mapping -- denoises BOLD then drives the share/rsfmri_pipeline Python steps.",
    "KUL_NIS/KUL_anat_biascorrect.sh": "N4 bias-field-corrects structural (T1/T2/FLAIR) BIDS images.",
    "KUL_NIS/KUL_anat_register.sh": "Rigid/affine/SyN registration of structural images to the subject's T1w and/or MNI.",
    "KUL_NIS/KUL_anat_lesionheatmap.sh": "Builds a group lesion-overlap heat map in MNI space after tumor segmentation.",
    "KUL_NIS/KUL_anat_segment_tumor.sh": "AI-based brain tumor / resection-cavity segmentation (HD-GLIO-AUTO, with FSL FAST / FastSurfer fallbacks).",
    "KUL_NIS/KUL_anat_b2subject.sh": "Small utility warping an MNI-space image back into subject space via fMRIPrep's inverse transform.",
    "KUL_NIS/KUL_T1T2FLAIRMTR_ratio.sh": "Computes T1/T2, T1/FLAIR, and MTR ratio maps (Ganzetti/Pareto method) for lesion characterisation.",
    "KUL_NIS/KUL_MS_lesion_stats.sh": "Multiple-sclerosis lesion statistics via FreeSurfer SAMSEG segmentation plus the ratio maps above.",
    "KUL_NIS/KUL_lesion_fs_recall.sh": "Dev/WIP: FreeSurfer recon-all on lesioned brains via a lesion-fill-and-swap technique -- superseded by KUL_VBG.",
    "KUL_NIS/KUL_FS_multiparc.sh": "FreeSurfer recon-all plus multi-scale parcellation (Lausanne/Glasser/thalamic/brainstem) for non-lesioned subjects.",
    "KUL_NIS/KUL_dsc_perfusion.sh": "Full DSC-MRI perfusion pipeline: motion/EPI correction, deconvolution, normalisation against contralesional white matter.",
    "KUL_NIS/share/dsc/KUL_dsc_fit.py": "DSC-MRI quantification worker: dR2* computation, leakage correction, SVD deconvolution to rCBV/rCBF/MTT maps.",
    "KUL_NIS/KUL_tracts_ocd.sh": "Named-project script generating slMFB/ATR tract bundles for OCD patients.",
    "KUL_NIS/KUL_karawun_prepare.sh": "Packages fMRI/DTI results (tracts, VOIs, activation maps) for export to Brainlab Elements Server via Karawun.",
    "KUL_NIS/KUL_karawun2brainlab.sh": "Older, simpler Karawun export -- superseded by KUL_karawun_prepare.sh.",
    "KUL_NIS/KUL_mrview_figure.sh": "Shared screenshot/visualisation utility -- renders TRA/SAG/COR mrview PNGs or montages; called as a subprocess by ~10 other scripts.",
    "KUL_NIS/KUL_MRtrix3_connectome.sh": "Runs the dockerized mrtrix3_connectome structural-connectome pipeline.",
    "KUL_NIS/KUL_qsiprep.sh": "Runs qsiprep or mrtrix_connectome via Docker for diffusion preprocessing/connectomics.",
    "KUL_NIS/KUL_synb0.sh": "Runs Synb0-DISCO (susceptibility distortion correction without a reverse-phase-encode scan) via Docker.",
    "KUL_NIS/KUL_radsyndisco.sh": "Docker-free, work-in-progress reimplementation of synb0-disco -- references an undefined model path, likely broken.",
    "KUL_NIS/KUL_bids_crop.sh": "Crops the neck off a T1w image along the z-axis -- destructive, \"use at own risk\".",
    "KUL_NIS/KUL_DTI_ALPS/KUL_calc_DTIALPS.sh": "Computes the DTI-ALPS glymphatic index from predefined MNI spheres warped into native dMRI space.",
    "KUL_NIS/KUL_bids_summary.sh": "Generates a BIDS_info.tsv summary of scan metadata across a dataset.",
    "KUL_NIS/KUL_linux_givebackmyfiles.sh": "One-line chown utility to fix Docker-root-owned output files.",
    "KUL_NIS/KUL_conn_make_nets.sh": "Named-project (hardcoded paths) network-map extraction from a CONN toolbox first-level analysis.",
    "KUL_NIS/KUL_reg_pwi_2_T1.sh": "Named-project (hardcoded personal path) one-off registering perfusion-weighted images to T1w.",
    "KUL_NIS/KUL_VSC_prepare_dwiprep.sh": "Abandoned/broken HPC job-prep fragment for the Vlaams Supercomputer Centrum -- undefined variables, missing template.",
    "KUL_NIS/KUL_EDs_b2masks.py": "Distance-metric toolkit for binary NIfTI masks (Hausdorff, ASSD, etc.) with parallel computation and mrview snapshotting.",
    "KUL_NIS/KUL_FAT1w.py": "Computes a FAT1w (sqrt(FA)xT1w) QA volume via MRtrix3 subprocess calls.",
    "KUL_NIS/KUL_nii2dcm.py": "Converts NIfTI results back to DICOM for PACS/Karawun export, built on SimpleITK.",
    "KUL_NIS/KUL_BIDS_clean.py": "Deduplicates multiple T1w/T2w/FLAIR runs per subject by inspecting JSON sidecars (manual/orphan tool).",
    "KUL_NIS/KUL_eddy_squad.py": "Standalone QC visualisation (violin plots) for FSL eddy-squad JSON output.",
    "KUL_NIS/KUL_main_functions.sh": "Shared library sourced by ~40 entry points -- defines KUL_task_exec (the parallel task runner nearly every call flows through) and conda-env bootstrap helpers.",
    "KUL_NIS/share/rsfmri_pipeline/src/step0_synthseg.sh": "Runs SynthSeg + 5ttgen tissue segmentation and MNI warping per subject, feeding the rsfMRI network pipeline.",
    "KUL_NIS/share/rsfmri_pipeline/src/run_pipeline.py": "Orchestrates the resting-state network pipeline's Python steps 1-4 as in-process function calls.",
    "KUL_NIS/share/rsfmri_pipeline/src/step1_sba.py": "Seed-based functional connectivity analysis.",
    "KUL_NIS/share/rsfmri_pipeline/src/step2_rsn_fc.py": "Resting-state-network-level functional connectivity matrix and whole-brain maps.",
    "KUL_NIS/share/rsfmri_pipeline/src/step3_masked_ica.py": "RSN-masked independent component analysis.",
    "KUL_NIS/share/rsfmri_pipeline/src/step3b_whole_brain_ica.py": "Whole-brain unconstrained ICA (standalone-only, not part of the automated run).",
    "KUL_NIS/share/rsfmri_pipeline/src/step4_compare.py": "Normative z-score comparison of a patient's networks against a healthy-volunteer baseline.",
    "KUL_NIS/share/rsfmri_pipeline/src/step5_report.py": "Full normative PDF report (needs step4's baseline output).",
    "KUL_NIS/share/rsfmri_pipeline/src/step5_lite_report.py": "Patient-own-data PDF/HTML report that doesn't require a normative baseline.",
    "KUL_NIS/share/rsfmri_pipeline/src/config.py": "Library: condition/seed profiles and path constants for the rsfMRI pipeline.",
    "KUL_NIS/share/rsfmri_pipeline/src/utils.py": "Library: ~45 shared helpers (I/O, atlas loading, FC computation) used by every rsfMRI pipeline step.",
    "KUL_NIS/tools/send_2_orthanc.sh": "Sends extracted DICOM zips to an Orthanc PACS server (placeholder credentials need manual editing).",
    "KUL_NIS/tools/KUL_DSC_analysis/DSC_proc_script_WIP3.sh": "Superseded DSC-perfusion prototype -- replaced by KUL_dsc_perfusion.sh + share/dsc/KUL_dsc_fit.py.",
    "KUL_NIS/tools/KUL_DSC_analysis/Good_DSCLC_fit5.py": "Superseded DSC-perfusion fitting prototype -- share/dsc/KUL_dsc_fit.py is its vectorised rewrite.",
    "KUL_NIS/VSC/Env_T1T2FLAIRMTR_cpu.sh": "Sourced (not run) HPC environment setup for the Vlaams Supercomputer Centrum, CPU variant.",
    "KUL_NIS/VSC/Env_T1T2FLAIRMTR_gpu.sh": "Sourced (not run) HPC environment setup for the Vlaams Supercomputer Centrum, GPU variant.",
    "KUL_NIS/KUL_DRT.sh": "Dentato-rubro-thalamic tract workflow -- drives multiscale brain parcellation (MSBP) and KUL_FWT tractography for this specific bundle.",
    "KUL_NIS/KUL_preproc_all.sh": "Thin dispatcher that runs fMRIPrep, dwiprep (via qsiprep-style prep), and/or FreeSurfer for a subject, called by KUL_clinical_fmridti.sh.",
    "KUL_NIS/share/nilearn/KUL_nilearn_glm.py": "Subprocess worker that runs the actual nilearn first-level GLM fit for KUL_fmriproc_nilearn_new.sh.",
    "KUL_NIS/atlases/lausanne2008/remap_lausanne_to_msbp.py": "Remaps Lausanne2008 atlas labels to the Multi-Scale Brain Parcellator (MSBP) numbering scheme (duplicate of the copy shipped inside KUL_VBG).",
    "KUL_NIS/atlases/lausanne2008/generate_msbp_luts.py": "One-off utility generating MSBP lookup tables (not invoked at runtime; duplicate of the copy shipped inside KUL_VBG).",
    "KUL_NIS/atlases/lausanne2008/make_readable_lut.py": "One-off utility converting a raw LUT into a human-readable format (not invoked at runtime; duplicate of the copy shipped inside KUL_VBG).",
    "KUL_NIS/share/spm12/spm12_fmri_stats_1run.m": "SPM12 batch script: first-level GLM stats for a single-run task-fMRI acquisition.",
    "KUL_NIS/share/spm12/spm12_fmri_stats_1run_job.m": "SPM12 batch parameter file loaded by spm12_fmri_stats_1run.m.",
    "KUL_NIS/share/spm12/spm12_fmri_stats_2runs.m": "SPM12 batch script: first-level GLM stats for a two-run task-fMRI acquisition.",
    "KUL_NIS/share/spm12/spm12_fmri_stats_2runs_job.m": "SPM12 batch parameter file loaded by spm12_fmri_stats_2runs.m.",
    "KUL_NIS/share/spm12/spm12_fmri_stats_3runs.m": "SPM12 batch script: first-level GLM stats for a three-run task-fMRI acquisition.",
    "KUL_NIS/share/spm12/spm12_fmri_stats_3runs_job.m": "SPM12 batch parameter file loaded by spm12_fmri_stats_3runs.m.",
    "KUL_NIS/share/spm12/spm12_new_fmri_stats_1run.m": "Newer-algorithm SPM12 batch script: first-level GLM stats, single run.",
    "KUL_NIS/share/spm12/spm12_new_fmri_stats_1run_job.m": "SPM12 batch parameter file loaded by spm12_new_fmri_stats_1run.m.",
    "KUL_NIS/share/spm12/spm12_new_fmri_stats_2runs.m": "Newer-algorithm SPM12 batch script: first-level GLM stats, two runs.",
    "KUL_NIS/share/spm12/spm12_new_fmri_stats_2runs_job.m": "SPM12 batch parameter file loaded by spm12_new_fmri_stats_2runs.m.",
    "KUL_NIS/share/spm12/spm12_new_fmri_stats_3runs.m": "Newer-algorithm SPM12 batch script: first-level GLM stats, three runs.",
    "KUL_NIS/share/spm12/spm12_new_fmri_stats_3runs_job.m": "SPM12 batch parameter file loaded by spm12_new_fmri_stats_3runs.m.",
    "KUL_NIS/share/spm12/spm12_threshold_Bizzi.m": "MATLAB-side statistical thresholding for the SPM GLM results (Bizzi method), invoked from KUL_fmriproc_spm_new.sh.",
    "KUL_NIS/studies/cappelle2021/convert2bids.sh": "Named-study (cappelle2021) one-off: DICOM-to-BIDS conversion for that study's cohort.",
    "KUL_NIS/studies/cappelle2021/convert_extra2bids.sh": "Named-study (cappelle2021) one-off: converts additional/extra scans to BIDS.",
    "KUL_NIS/studies/cappelle2021/KUL_samseg_longitudinal.py": "Named-study (cappelle2021) one-off: longitudinal SAMSEG lesion-volume analysis.",
    "KUL_NIS/studies/cappelle2021/KUL_warp_lesions2mni.py": "Named-study (cappelle2021) one-off: warps lesion masks into MNI space.",
    "KUL_NIS/studies/cappelle2021/KUL_plot_histograms.m": "Named-study (cappelle2021) one-off: plots result histograms in MATLAB.",
    "KUL_NIS/studies/cappelle2021/KUL_plot_stats.m": "Named-study (cappelle2021) one-off: plots summary statistics in MATLAB.",
    "KUL_NIS/studies/verhaaren2022/KUL_DRT_determine_position.py": "Named-study (verhaaren2022) one-off: determines DRT tract position for that study's analysis.",
    "KUL_VBG/Docker/build.sh": "Build-helper CLI wrapping `docker build`/`apptainer build` for the KUL_VBG container image -- packaging tooling, not part of the runtime pipeline.",
    "KUL_VBG/Docker/entrypoint.sh": "Container runtime shim: sets up FreeSurfer/FSL/ANTs env vars and licence, then execs the user's KUL_VBG command.",
    "KUL_FWT/dev_work/KUL_Voxel_mask_segment3.py": "Earlier iteration of KUL_Voxel_mask_segment.py (PCA-based mask segmentation) -- experimental scratch, not called by the pipeline.",
    "KUL_FWT/dev_work/KUL_Voxel_mask_segment4.py": "Later experimental iteration of KUL_Voxel_mask_segment.py, adding a num_segments parameter -- scratch, not called by the pipeline.",
    "KUL_FWT/dev_work/slices_maps.py": "Scratch utility generating NIfTI slice images in parallel -- not called by the pipeline.",

    # --- KUL_VBG ---
    "KUL_VBG/KUL_VBG.sh": "Main driver: excises a brain lesion from T1, fills the defect with synthetic/contralateral-derived tissue, then runs FreeSurfer/FastSurfer/SynthSeg parcellation on the result.",
    "KUL_VBG/KUL_VBG_multiparc.sh": "Standalone multi-scale parcellation (Lausanne/Glasser/thalamic/brainstem/hippocampus) runnable on any completed FreeSurfer output, VBG or not.",
    "KUL_VBG/KUL_VBG_cook_template.sh": "Manual, edit-and-run utility that builds a population/scanner-specific VBG template from two contralaterally-lesioned patients.",
    "KUL_VBG/KUL_synth_pats_4VBG.sh": "Research utility generating synthetic lesioned-brain cohorts for validation, combining real lesions with healthy-volunteer T1s.",
    "KUL_VBG/KUL_VBG_QC.py": "Generates a QC HTML report for the VBG inpainting result -- similarity metrics and an artifact/failure-mode report.",
    "KUL_VBG/KUL_lesion_overlap.py": "Computes per-label volumetric overlap between a parcellation and a lesion mask.",
    "KUL_VBG/atlasses/New/atlases/lausanne2008/remap_lausanne_to_msbp.py": "Remaps Lausanne2008 atlas labels to the Multi-Scale Brain Parcellator (MSBP) numbering scheme.",
    "KUL_VBG/atlasses/New/atlases/lausanne2008/generate_msbp_luts.py": "One-off utility generating MSBP lookup tables (not invoked at runtime by the pipeline).",
    "KUL_VBG/atlasses/New/atlases/lausanne2008/make_readable_lut.py": "One-off utility converting a raw LUT into a human-readable format (not invoked at runtime by the pipeline).",

    # --- KUL_FWT ---
    "KUL_FWT/KUL_FWT_make_VOIs.sh": "Generates every anatomical inclusion/exclusion VOI tractography needs, per subject, from FreeSurfer's aparc+aseg plus MNI atlases.",
    "KUL_FWT/KUL_FWT_make_VOIs_4Temp.sh": "Same VOI-generation workflow, retargeted for group-averaged template data.",
    "KUL_FWT/KUL_FWT_make_TCKs.sh": "Generates every fiber bundle from the config list, using the VOIs above -- 4 tracking approaches, 3 filtering levels.",
    "KUL_FWT/KUL_FWT_make_TCKs_4Temp.sh": "Template/group-data counterpart of KUL_FWT_make_TCKs.sh.",
    "KUL_FWT/KUL_FWT_tractometry_functions.sh": "Shared library (sourced only under -Q) computing per-bundle along-tract metric profiles.",
    "KUL_FWT/KUL_FWT_FBC_4TCKs.py": "Filters a tractogram using DIPY's Fiber-to-Bundle Coherence measure.",
    "KUL_FWT/KUL_FWT_reject_outliers.py": "Rejects outlier streamlines from one bundle (the filt3 step), bounding the cut by an absolute score floor and by a share of the bundle; replaces scil_bundle_reject_outliers.",
    "KUL_FWT/KUL_FWT_plot_bundle_connectivity.py": "Builds a per-bundle endpoint-connectivity matrix and plot.",
    "KUL_FWT/KUL_FWT_SCs_TCKs.py": "AFQ-style along-tract profile analysis for filtered bundles.",
    "KUL_FWT/KUL_FWT_bundle_spider_plot.py": "Aggregates every bundle's tractometry output into one subject-level radar/spider chart.",
    "KUL_FWT/KUL_FWT_bundle_report.py": "Collects per-bundle screenshots into one self-contained HTML contact-sheet report per subject.",
    "KUL_FWT/KUL_FWT_buan_profile.py": "Leaf worker computing one bundle's along-tract scalar profile for one metric (DIPY afq_profile).",
    "KUL_FWT/KUL_FWT_morphometrics.py": "Standalone: computes tractogram morphological features (volume, surface area via marching cubes).",
    "KUL_FWT/KUL_FWT_plot_fixel_bundle_metrics.py": "Standalone: plots mean fixel-derived bundle metrics from a CSV.",
    "KUL_FWT/KUL_FWT_TCKsm_cap.py": "Unfinished standalone visualisation scaffold for TCK-derived segmentation maps.",
    "KUL_FWT/KUL_Voxel_mask_segment.py": "Standalone: splits a binary voxel mask into segments along its principal axis (PCA).",
}

TOOL_INFO = {
    # FreeSurfer
    "recon-all": "FreeSurfer's full cortical reconstruction pipeline -- skull-strips, segments, and surface-models a T1 image.",
    "mri_convert": "FreeSurfer's general-purpose image format/geometry converter.",
    "mri_synthstrip": "Deep-learning skull-stripping that works across MRI contrasts without retraining.",
    "mri_synthseg": "Deep-learning whole-brain segmentation, robust to contrast, resolution, and pathology.",
    "SynthSeg": "Deep-learning whole-brain segmentation, robust to contrast, resolution, and pathology.",
    "mri_segment_hypothalamic_subunits": "Automated segmentation of hypothalamic subunits from a T1 image.",
    "mri_surf2surf": "Resamples data between cortical surface meshes (e.g. subject <-> fsaverage).",
    "mri_annotation2label": "Converts a FreeSurfer cortical parcellation annotation into individual ROI label files.",
    "mri_mask": "Applies a binary mask to an image, zeroing everything outside it.",
    "mri_aparc2aseg": "Projects a cortical surface parcellation into the volumetric aseg segmentation.",
    "mri_vol2vol": "Resamples a volume into another volume's space using a given transform.",
    "segment_subregions": "FreeSurfer's automated subregion segmentation (thalamus / brainstem / hippocampus-amygdala).",
    "samseg": "FreeSurfer's sequence-adaptive, pathology-robust whole-brain segmentation.",
    "run_samseg": "FreeSurfer's sequence-adaptive, pathology-robust whole-brain segmentation.",
    "mris_register": "Registers a subject's cortical surface to a spherical atlas (runs internally inside recon-all).",
    # FastSurfer
    "run_fastsurfer": "Deep-learning alternative to FreeSurfer's recon-all -- whole-brain segmentation + surfaces in minutes.",
    "run_fastsurfer.sh": "Deep-learning alternative to FreeSurfer's recon-all -- whole-brain segmentation + surfaces in minutes.",
    "fastsurfer": "Deep-learning alternative to FreeSurfer's recon-all -- whole-brain segmentation + surfaces in minutes.",
    # ANTs
    "antsRegistration": "ANTs' general-purpose deformable/affine image registration engine.",
    "antsRegistrationSyN.sh": "ANTs' standard rigid+affine+SyN registration recipe, wrapped as a one-call script.",
    "antsRegistrationSyN": "ANTs' standard rigid+affine+SyN registration recipe, wrapped as a one-call script.",
    "antsApplyTransforms": "Applies a previously computed ANTs transform to resample an image into another space.",
    "antsBrainExtraction.sh": "ANTs' template-based brain extraction (skull-stripping).",
    "antsBrainExtraction": "ANTs' template-based brain extraction (skull-stripping).",
    "antsAtroposN4.sh": "Combines N4 bias correction with Atropos tissue segmentation in one pipeline.",
    "antsAtroposN4": "Combines N4 bias correction with Atropos tissue segmentation in one pipeline.",
    "Atropos": "ANTs' n-tissue-class segmentation (EM/MRF-based).",
    "ImageMath": "ANTs' Swiss-army-knife image arithmetic/morphology utility.",
    "WarpImageMultiTransform": "Applies one or more ANTs transforms/warps to an image (older ANTs transform tool).",
    "antsMotionCorr": "ANTs' rigid-body motion correction for time-series (e.g. DSC/fMRI) data.",
    "ConvertTransformFile": "Converts an ANTs transform between file formats/representations.",
    "N4BiasFieldCorrection": "Corrects smooth intensity (bias-field) inhomogeneity in an MR image.",
    "N4": "Corrects smooth intensity (bias-field) inhomogeneity in an MR image.",
    # FSL
    "fslmaths": "FSL's voxel-wise image calculator (arithmetic, thresholding, filtering).",
    "fslstats": "Reports summary statistics (mean, min/max, percentiles) over an image or masked region.",
    "fslreorient2std": "Reorients an image's axes to match FSL's standard (MNI-like) orientation convention.",
    "fslswapdim": "Reorders/flips an image's axes.",
    "fslorient": "Reads or edits an image's orientation/sform-qform header fields.",
    "bet": "FSL's classic brain extraction (skull-stripping) tool.",
    "flirt": "FSL's linear (rigid/affine) image registration tool.",
    "fslmerge": "Concatenates multiple 3D images into a 4D time series (or vice versa).",
    "fsl_glm": "Fits a general linear model to timeseries or scalar data.",
    "slicer": "Generates PNG slice-mosaic screenshots of a volume for QC.",
    "susan": "FSL's edge-preserving (non-linear) smoothing filter.",
    "topup": "Estimates and corrects susceptibility-induced distortion from reversed-phase-encode acquisitions.",
    "fast": "FSL's tissue-type segmentation (CSF/GM/WM) with bias-field correction.",
    # mrtrix3
    "mrcalc": "mrtrix3's voxel-wise image calculator -- the general-purpose arithmetic/logic workhorse used throughout this codebase.",
    "mrstats": "Reports summary statistics over an image, optionally within a mask.",
    "mrthreshold": "Thresholds an image into a binary mask (fixed value, percentile, or Otsu).",
    "maskfilter": "Applies morphological operations (dilate/erode/clean/connect) to a binary mask.",
    "mrfilter": "Applies filters (Gaussian smoothing, gradient, etc.) to an image.",
    "labelconvert": "Relabels a parcellation image from one lookup table's numbering scheme to another's.",
    "mrmath": "Computes a statistic (mean, sum, max...) across a set of images or across a 4D image's volumes.",
    "mrconvert": "mrtrix3's general-purpose image format/metadata converter -- the toolkit's Swiss-army entry point.",
    "mrinfo": "Prints an image's header metadata (dimensions, voxel size, orientation, gradient table).",
    "mrgrid": "Regrids/crops/pads/resamples an image onto a new voxel grid.",
    "mrview": "mrtrix3's interactive image/tractogram viewer, also used headlessly for screenshots.",
    "mrtransform": "Applies a spatial transform/warp to reorient or resample an image.",
    "mrcat": "Concatenates images along a new or existing axis (e.g. combining phase-encode directions).",
    "mrresize": "Changes an image's voxel size/resolution by resampling.",
    "dwifslpreproc": "Wraps FSL's topup+eddy for combined susceptibility- and motion/eddy-current correction of DWI data.",
    "dwidenoise": "MP-PCA denoising of diffusion-weighted images.",
    "dwibiascorrect": "Corrects intensity bias field in diffusion-weighted images (via ANTs N4 or FSL FAST).",
    "mrdegibbs": "Removes Gibbs-ringing artifact from MR images.",
    "dwi2mask": "Generates a brain mask directly from diffusion-weighted data.",
    "dwi2response": "Estimates the fibre response function(s) needed for spherical deconvolution.",
    "dwi2fod": "Computes fibre orientation distributions (FODs) via constrained spherical deconvolution.",
    "dwi2tensor": "Fits the diffusion tensor model to DWI data.",
    "tensor2metric": "Derives scalar maps (FA, MD, RD, AD...) from a fitted diffusion tensor.",
    "tckgen": "Performs streamline tractography (deterministic or probabilistic) from FOD/tensor data.",
    "tcksift": "Filters a tractogram so streamline density better matches the diffusion signal (SIFT).",
    "tcksift2": "Reweights (rather than removes) streamlines so density matches the diffusion signal (SIFT2).",
    "tckedit": "Selects, merges, or filters streamlines from one or more tractograms.",
    "tckmap": "Converts a tractogram into a voxel-wise density or scalar map.",
    "tckstats": "Reports summary statistics over a tractogram (e.g. streamline count, length).",
    "tckresample": "Resamples streamlines to a fixed number of points or fixed step size.",
    "tcksample": "Samples an image's values along each streamline of a tractogram.",
    "dwiextract": "Extracts a subset of volumes (e.g. by b-value or phase-encode direction) from DWI data.",
    "dwigradcheck": "Checks/corrects the sign and ordering of a DWI gradient table against the image data.",
    "5ttgen": "Generates a 5-tissue-type (5TT) segmented image for anatomically-constrained tractography.",
    "5tt2gmwmi": "Derives a grey-matter/white-matter interface mask from a 5TT image, for GMWMI seeding.",
    "mtnormalise": "Performs multi-tissue log-domain intensity normalisation across FOD images.",
    "population_template": "Builds an unbiased group-average template (e.g. FOD template) from multiple subjects.",
    "responsemean": "Averages per-subject response functions into a group-representative one.",
    "voxel2fixel": "Maps a voxel-wise scalar image onto a fixel (fibre-bundle-element) dataset.",
    "warpinit": "Creates an identity warp image, used to later invert/compose spatial transforms.",
    "fixel2voxel": "Projects fixel-wise data back onto a voxel-wise scalar image.",
    "fod2fixel": "Extracts discrete fixels (individual fibre populations) from FOD images.",
    "tck2fixel": "Maps streamline/tractogram-derived quantities onto a fixel dataset.",
    # scilpy
    "scil_reco_bundles": "Segments a whole-brain tractogram into named bundles via RecoBundles atlas matching.",
    "scil_bundle_compute_centroid": "Computes a bundle's centroid streamline.",
    "scil_bundle_reject_outliers": "Removes anatomically implausible outlier streamlines from a bundle.",
    "scil_bundle_uniformize_endpoints": "Flips streamlines so a bundle's endpoints are consistently oriented (e.g. matching a reference centroid).",
    "scil_bundle_label_map": "Assigns along-tract position labels to a bundle's streamlines.",
    "scil_filter_tracts": "Filters streamlines by geometric/anatomical criteria.",
    "scil_tractogram_convert": "Converts a tractogram between file formats (e.g. .tck <-> .trk).",
    "scil_tractogram_detect_loops": "Flags/removes streamlines that loop back on themselves.",
    "scil_tractogram_filter_by_roi": "Keeps or removes streamlines based on inclusion/exclusion ROIs.",
    "scil_tractogram_segment_with_recobundles": "Segments a tractogram into bundles using the RecoBundles method.",
    "scil_tractogram_smooth": "Smooths streamline trajectories.",
    "scil_vis_mosaic": "Renders bundle screenshots arranged as a mosaic, for QC reports.",
    "scil_viz_bundle_screenshot_mni": "Renders a bundle screenshot in MNI space, for QC reports.",
    "scil_viz_bundle_screenshot_mosaic": "Renders bundle screenshots for QC reports.",
    # AI segmentation
    "hd-bet": "Deep-learning brain extraction (skull-stripping), robust across MR contrasts and pathology.",
    "HD-BET": "Deep-learning brain extraction (skull-stripping), robust across MR contrasts and pathology.",
    "hd-glio-auto": "Deep-learning automated glioma segmentation (enhancing tumor, edema, necrosis).",
    "hd-glio-predict": "Deep-learning automated glioma segmentation (enhancing tumor, edema, necrosis).",
    "resseg": "Deep-learning segmentation of a brain resection cavity.",
    # export/DICOM
    "karawun": "Packages neuroimaging results (tracts, activations, VOIs) into a format Brainlab surgical navigation systems can import.",
    "dcm2niix": "Converts DICOM images to NIfTI.",
    "dcm2bids": "Organizes dcm2niix output into a BIDS-compliant dataset structure.",
    "dcm2bids_scaffold": "Creates the initial folder/config scaffold for a Dcm2Bids conversion.",
    "dcmsend": "DCMTK tool that sends DICOM files to a PACS server.",
    "7z": "General-purpose file archiver/compressor.",
    # containers
    "docker": "Container runtime used to run tools packaged as images (e.g. hd-glio-auto, qsiprep, synb0).",
    "singularity": "HPC-friendly container runtime, an alternative to Docker (predecessor to Apptainer).",
    "apptainer": "HPC-friendly container runtime, an alternative to Docker (successor to Singularity).",
    # MATLAB/SPM
    "matlab": "MATLAB runtime, used here to execute SPM12 batch scripts.",
    "spm12": "SPM12 -- MATLAB-based statistical parametric mapping toolbox for fMRI/VBM analysis.",
    # distortion correction
    "synb0": "Synb0-DISCO -- synthesizes an undistorted b0 image via deep learning, enabling susceptibility correction without a reverse-phase-encode scan.",
    # pipelines
    "fmriprep": "Automated, robust fMRI preprocessing pipeline (motion correction, registration, confound estimation).",
    "qsiprep": "Automated diffusion MRI preprocessing pipeline -- fMRIPrep's counterpart for dMRI.",
    "mrtrix_connectome": "Dockerized end-to-end structural connectome pipeline built on mrtrix3.",
    "mriqc": "Automated MRI quality-control metrics and reports.",
    "tedana": "Multi-echo fMRI denoising via TE-dependent ICA component classification.",
    # viz / misc
    "freeview": "FreeSurfer's interactive volume/surface viewer.",
    "csvkit": "Command-line utilities for working with CSV files.",
}
